---
verifiers-config:
  output:
    template-text-file: "verifiers/verifiers_texts.yaml"
  common:
    default-verifier-tag-mapping: "verifiers/default_tag_mapping.yaml"
    errors:
      default-severity: error
    strip-context:                                    # Value inside these characters (includsive) will be stripped for the purpose of reference comparisons e.g. if valie is "database (SQL)" then only "database" is used
      start-char: "("
      end-char: ")"
    exclude:
      tag-prefix: "exclude"                           # Look for tags beginning with this when deciding if a value should be excluded
    references:
      doc-tag-prefix: "ref"                           # reference tags beginning with this will cause reference validation to look in the threat model document for the reference
      templ-tag-prefix: "tref"                        # reference tags beginning with this will cause reference validation to look in the threat model template for the reference
    component-tags:
      component-data-tag: components-details-data     # data with this tag will be used to extract the components of the threat model
      component-in-scope-tag: in-scope                # within the component-data-tag, values with this tag will indicate if the component is in-scope
      component-in-scope-value: {{ translate.yes }}   # the value to use to determine if a component is in-scope
    asset-tags:
      asset-data-tag:
        - functional-asset-data                       # data with this tag will be used to extract the functional assets of the threat model
        - technical-asset-data                        # data with this tag will be used to extract the technical assets of the threat model
      asset-location-tag: storage-location
    threat-tags:
      threats-data-tag: threats-and-controls-data     # data with this tag will be used to extract the threats and controls of the threat model
      threat-asset-tag: threat-asset                  # within the threats-data-tag, values with this tag will be used to extract the assets covered by a threat
      threat-component-tag: threat-component          # within the threats-data-tag, values with this tag will be used to extract the components covered by a threat
      threat-description-tag: threat-description      # within the threats-data-tag, values with this tag will be used to extract the description of a threat
      threat-control-tag: threat-control              # within the threats-data-tag, values with this tag will be used to extract the controls of a threat
    # 'grouped-text' gets copied from verifiers_texts.yaml
  
  coverage-validation:                                # coverage-validation configuration (mostly uses value from 'common')
  
  reference-validation:                               # reference-validation configuration (mostly uses value from 'common')
  
  field-validation-mandatory:                         # verifier for mandatory fields
    default: True                                     # whether or not, by default, all values should be considered mandatory
    exceptions-tag: "not-mandatory"                   # if 'default' is 'True' then any value with this tag will not be mandatory
  
  field-validation-conditional-mandatory:             # verifier for a value must exist if another value has a certain value
    tags:
    # The following pairs of tag define a tag that is mandatory if another tag has a value
      #- tag: "tech-stack"                             # in any given row, the value tagged 'tech-stack' is mandatory if
      #  depends-on: "in-scope"                        # the value tagged 'in-scope'
      #  depends-on-value: {{ translate.yes }}         # has this value
      #- tag: "version-approver"
      #  depends-on: "version-status"
      #  depends-on-value: {{ translate.approved }}
      #- tag: "version-approved-date"                  # in any given row, the value tagged 'version-approved-date' is mandatory if
      #  depends-on: "version-approver"                # the value tagged 'version-approver' has ANY value
      #- tag: "version-approver"                       # in any given row, the value tagged 'version-approver' is mandatory if
      #  depends-on: "version-approved-date"           # the value tagged 'version-approved-date' has ANY value

  field-validation-conditional:                      # verifier for a value with a condition if another value has a certain value
    conditionals:
    # The following are conditional 'if ... then ...' statements where if the 'if' condition is True and the 'then' condition is false, an issue is raised
      # If 'In Scope' is 'Yes' then 'Tech Stack' must not be empty
      - if:
          value-tag: "in-scope"
          value-condition:
            validator: "string"
            config:
              method: "equals"
              expected-result: {{ translate.yes }}
        then:
          value-tag: "tech-stack"
          value-condition:
            validator: "string"
            config:
              method: "isnotempty"
        issue-text-key: conditional-mandatory
      # If 'In Scope' is 'Yes' then 'Component' name must exist in the 'AuthN/Z' table
      - if:
          value-tag: "in-scope"
          value-condition:
            validator: "string"
            config:
              method: "equals"
              expected-result: {{ translate.yes }}
        then:
          value-tag: "name"
          value-condition:
            validator: "exists"
            config:
              template: false
              data-tag: "components-access-control-data"
              value-tag: "threat-component"
        issue-text-key: conditional-mandatory-exists
        fix-text-key: conditional-mandatory-exists-fix
        issue-table-tag: "components-access-control-data"       # When there's an error, use the table with this tag
        issue-table-row:                                        # When there's an error, leaving this blank means no (row) location is shown
        issue-key-tag: "threat-component"                       # When there's an error, the 'issue_key' used in templates has this tag
      # If 'Status' is 'Approved' then 'Approver Name' must not be empty
      - if:
          value-tag: "version-status"
          value-condition:
            validator: "string"
            config:
              method: "equals"
              expected-result: {{ translate.approved }}
        then:
          value-tag: "version-approver"
          value-condition:
            validator: "string"
            config:
              method: "isnotempty"
        issue-text-key: "conditional-mandatory"
      # If 'Approver Name' is not empty then 'Approved Date' must also be not empty
      - if:
          value-tag: "version-approver"
          value-condition:
            validator: "string"
            config:
              method: "isnotempty"
        then:
          value-tag: "version-approved-date"
          value-condition:
            validator: "string"
            config:
              method: "isnotempty"
        issue-text-key: "conditional-mandatory-any-value"
      # If 'Approver Name' is empty then 'Approved Date' must also be empty
      - if:
          value-tag: "version-approver"
          value-condition:
            validator: "string"
            config:
              method: "isempty"
        then:
          value-tag: "version-approved-date"
          value-condition:
            validator: "string"
            config:
              method: "isempty"
        issue-text-key: "conditional-is-empty"
      # If 'Authentication' is 'n/a' then 'Authorisation' must also be 'n/a' i.e. if authn is not possible, then authz is not possible.  Usually authors mean authn is 'None' i.e. there is no authn
      - if:                                            
          value-tag: "authentication"
          value-condition:
            validator: "string"
            config:
              method: "equals"
              expected-result: {{ translate.na | safe }}
        then:
          value-tag: "authorisation"
          value-condition:
            validator: "string"
            config:
              method: "equals"
              expected-result: {{ translate.na | safe }}
        issue-text-key: "conditional-authnz-na"
        fix-text-key: "conditional-authnz-na-fix"
      # If 'Authorisation' is 'n/a' then 'Authentication' must also be 'n/a' i.e. if authz is not possible, then authn is not possible.  Uusally authors mean authz is 'None' i.e. there is no authz
      - if:                                             
          value-tag: "authorisation"
          value-condition:
            validator: "string"
            config:
              method: "equals"
              expected-result: {{ translate.na | safe }}
        then:
          value-tag: "authentication"
          value-condition:
            validator: "string"
            config:
              method: "equals"
              expected-result: {{ translate.na | safe }}
        issue-text-key: "conditional-authnz-na"
        fix-text-key: "conditional-authnz-na-fix"
  
  field-validation-uniqueness:                        # verifier to check if a value is unique, according the criteria in it's tag
    unique-tag-prefix: "unique"                       # how to identity tags containing uniqueness criteria
    tags:                                             # Any key tagged with these tags must have a value that is document unique amongst all values for keys with the same tag
      - tag: document-unique
  
  field-validation-value:                             # verifier that runs all the possible field validators
    validator-config:
      validator-config-yaml-path: "validators/validators_config.yaml"
      validator-text-yaml-path: "validators/validators_text.yaml"
    not-mandatory-tag: "not-mandatory"                # we don't want to validate empty fields against our criteria, so for field validation, if a value is tagged not-mandatory, we don't fail validation if it is empty
    tags:                                             # the list of tags to look for on values to perform validation.  The validators these correspond to are in validators/validators_config.yaml
      - tag: validate-as-version
      - tag: validate-as-date
      - tag: validate-as-single-entry
      - tag: validate-as-yes-no
      - tag: validate-as-CIA
      - tag: validate-as-status
      - tag: validate-from-template
  
