---
response-config:
  output:
    template-text-file: response/response_texts.yaml
  html:
    scheme-specific:
      - regex: "^googledoc"
        inject:
          location:
            element: "//html/body"
            index: -1                                        # The index of the child element to insert the content at.  -1 means the last element
          inline:
            style: |
              body { 
                min-width: 80vh; 
                margin:auto;
              }
    banner:                                                 # The banner content will get added as the first child of the <body> tag
      text-keys:
        missing-findings: "html-banner-missing-findings"
      inject:
        location:
          element: "//html/body"
          index: 0                                        # The index of the child element to insert the content at.  -1 means the last element
        include:
          scripts:
          stylesheets:
        inline:
          element: |
            <div id="threatware-banner"></div>
          style: |
            #threatware-banner {
              /*display: flex;*/
              justify-content: left;
              width: 100%;
              min-height: 48px;
              padding-top: 1px;
              padding-bottom: 20px;
              padding-left: 30px;
              padding-right: 20px;
              line-height: normal;
              text-align: left;
              text-decoration: none;
              font-size: 24px;
              color: #181818;
              border-radius: 10px;
            }
            #threatware-banner[threatware-result="errors"] {
              background-color: #ffd6d6;
            }
            #threatware-banner[threatware-result="no-errors"] {
              background-color: #d6ffd6;
            }
          script: |
            const banner = document.getElementById("threatware-banner");
            if (banner) {
              // 'banner_msg' is set by a system added script
              banner.innerHTML = banner_msg;
              // 'threatware_result' is set by a system added script
              banner.setAttribute("threatware-result", threatware_result);
            }
    findings:                                               # The findings content will get added after the last child of the <body> tag
      finding-attributes:
        finding-index: "threatwarefinding"                  # The attribute that will be added to the locations of findings in the HTML, and contain the index of the finding in the results
        finding-type: "threatwarefinding-type"              # The attribute that will be added to the locations of findings in the HTML, and contain the type of finding e.g. error, warning, info
      inject:
        location:
          element: "//html/body"
          index: -1                                        # The index of the child element to insert the content at.  -1 means the last element
        include:
          scripts:
            - "https://unpkg.com/@popperjs/core@2.9.3/dist/umd/popper.min.js"
            - "https://unpkg.com/tippy.js@6/dist/tippy-bundle.umd.js"
          stylesheets:
            - "https://unpkg.com/tippy.js@6/themes/light.css"
            - "https://unpkg.com/tippy.js@6/themes/light-border.css"
            - "https://unpkg.com/tippy.js@6/themes/material.css"
            - "https://unpkg.com/tippy.js@6/themes/translucent.css"
            - "https://unpkg.com/tippy.js@6/animations/scale.css"
        inline:
          style: |
            [threatwarefinding-type="error"] {
              box-shadow: 0 0 5px 5px red;
            }
            [threatwarefinding-type="warning"] {
              box-shadow: 0 0 5px 5px gold;
            }
            [threatwarefinding-type="info"] {
              box-shadow: 0 0 5px 5px lightblue;
            }
            #tippytip {
              font-size: 1.3em;
            }
          script: |
            function formatfinding(finding) {
                  return `<div id="tippytip">
                  <h3>${finding["type"]} (${finding["verifier"]})</h3>
                  <p><b>Description:</b> ${finding["error-description"]}</p>
                  <p>${finding["fix-description"] ? `<b>Fix-Description:</b> ${finding["fix-description"]}` : ""}</p>
                  <p>${finding["fix-data"] ? `<b>Fix-Data:</b> ${finding["fix-data"]}` : ""}</p>
                  </div>`
              }
            // Call `tippy()` with a CSS selector and a `content` prop:
            tippy('[threatwarefinding]', {
              theme: 'light-border',
              animation: 'scale',
              placement: 'right',
              maxWidth: 650,
              content(reference) {
                const id = reference.getAttribute('threatwarefinding');
                // There can be multiple findings for the same location, so the 'id' can be a space separated list of indexes
                const indexes = id.split(" ");
                template = "";
                for (let i = 0; i < indexes.length; i++) {
                    template += formatfinding(threatwarefindings[indexes[i]]);
                    if (indexes.length > 1) {
                        template += "<hr>";
                    }
                }
                return template;
              },
              allowHTML: true,
            });