---
validator-config:
  - tag: validate-as-version    # for any data tagged with 'validate-as-version'
    validator: regex            # invoke the regex validator
    config:
      pattern: "^\\d+.\\d+$"    # ensure the value matches this pattern
  - tag: validate-as-date
    validator: date
    config:
  - tag: validate-as-single-entry   # for any data tagged with 'validate-as-single-entry'
    validator: string               # invoke the string validator 
    config:
      method: "count"               # cound the number of occurances in the string (see validators/string.py for a list of methods)
      input-parameter: "\n"         # of the value "\n"
      expected-result: 0            # which should equal 0
  - tag: validate-as-yes-no
    validator: regex
    config:
      pattern: "(?i){{ translate.yes }}|{{ translate.no }}"
  - tag: validate-as-CIA
    validator: regex
    config:
      pattern: "(?i){{ translate.confidentiality }}|{{ translate.integrity }}|{{ translate.availability }}"
  - tag: validate-as-status
    validator: regex
    config:
      pattern: "(?i){{ translate.draft }}|{{ translate.approved }}|{{ translate.obsolete }}"
  - tag: validate-from-template
    validator: template
    config:
