---
validator-config:
  - tag: validate-as-version
    validator: regex
    config:
      pattern: "^\\d+.\\d+$"
  - tag: validate-as-date
    validator: date
    config:
  - tag: validate-as-single-entry
    validator: string
    config:
      method: "count"
      input-parameter: "\n"
      expected-result: 0
  - tag: validate-as-yes-no
    validator: regex
    config:
      pattern: "(?i){{ translate.yes }}|{{ translate.no }}"
  - tag: validate-as-CIA
    validator: regex
    config:
      pattern: "(?i){{ translate.confidentiality }}|{{ translate.integrity }}|{{ translate.availability }}"
  - tag: validate-as-status
    validator: regex
    config:
      pattern: "(?i){{ translate.draft }}|{{ translate.approved }}|{{ translate.obsolete }}"
  - tag: validate-from-template
    validator: template
    config:
