---
measure-config:
  #template-values-file: "verifiers/verifiers_values.yaml"
  measure-tag:
    prefix: "measure"
    measure-this-model-against-other-model: "from-this"
    measure-other-model-against-this-model: "from-other"
    measure-compare-tuple: "tuple"
    measure-compare-missing: "missing"
    measure-compare-extra: "extra"
  filters:
    3rd-parties:
      - {{ translate.third_party }}
      - {{ translate.threerd_party }}
      - {{ translate.SaaS }}
    internal-service:
      - {{ translate.internal_service }}
  output:
    template-text-file: "measure/measure_texts.yaml"