---
manage-config:
  #template-values-file: "verifiers/verifiers_values.yaml"
  storage:
    gitrepo:
      remote: "git@github.com-threat-models:samadhicsec/threat-models.git"
      #remote: "git@github.com:samadhicsec/threat-models.git"
      default-branch: "approved"
      base-storage-dir: "/tmp"
    index:
      index-create-branch: "create"
  metadata:
    index-filename: "threatmodels.yaml"
    metadata-filename: "metadata.yaml"
    approved-status: {{ translate.approved }}
  check:
    approval-expiry-days: 365
  output:
    template-text-file: "manage/manage_texts.yaml"