---
manage-config:
  #template-values-file: "verifiers/verifiers_values.yaml"
  storage:
    gitrepo:
      remote: "git@github.com-threat-models:samadhicsec/threat-models.git"
      #remote: "git@github.com:samadhicsec/threat-models.git"
      default-branch: "approved"
      base-storage-dir: "/tmp"
    index:
      index-create-branch: "create"
      # This is the key from manage_texts.yaml to use as a commit message when calling manage.create
      index-commit-message-text-key: "manage.create-commit-message"
    threatmodel:
      # This is the key from manage_texts.yaml to use as a commit message when calling manage.submit
      tm-commit-message-text-key: "manage.submit-commit-message"
  metadata:
    index-filename: "threatmodels.yaml"
    metadata-filename: "metadata.yaml"
    approved-status: {{ translate.approved }}
    write-plain-model: True
  check:
    approval-expiry-days: 365
  output:
    template-text-file: "manage/manage_texts.yaml"